---
- name: Copy config file from master to local.
  fetch:
    src: "~{{ ansible_ssh_user }}/.kube/config"
    dest: "config-{{ deploy_target }}"
    flat: true
  delegate_to: "{{ groups.masters[0] }}"
  run_once: true
  tags: ['kube']


