apiVersion: v1
kind: ConfigMap
metadata:
  name: index-a
data:
  index.html: |
    <html>
    <head><title>App A</title>
      <style>
        html {
          font-size: 62.5%;
        }
        body {
          font-family: sans-serif;
          background-color: midnightblue;
          color: white;
          display: flex;
          flex-direction: column;
          justify-content: center;
          height: 100vh;
        }
        div {
          text-align: center;
          font-size: 8rem;
          text-shadow: 3px 3px 4px dimgrey;
        }
      </style>
    </head>
    <body>
      <div>This is App A</div>
    </body>
    </html>
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: index-b
data:
  index.html: |
    <html>
    <head><title>App B</title>
      <style>
        html {
          font-size: 62.5%;
        }
        body {
          font-family: sans-serif;
          background-color: rgb(153, 52, 91);
          color: white;
          display: flex;
          flex-direction: column;
          justify-content: center;
          height: 100vh;
        }
        div {
          text-align: center;
          font-size: 8rem;
          text-shadow: 3px 3px 4px dimgrey;
        }
      </style>
    </head>
    <body>
      <div>This is App B</div>
    </body>
    </html>